inbound_pick_server:

  ik_sol_number: 512
  max_stall_iter: 512
  collision_detector: FCL

  groups:
    manipulator: open_tip

  manipulator:
    preferred_configuration: [1.4762239456176758, -1.7016049824156703, 1.7525199095355433, -0.6964729589274903, 1.4800915718078613, -2.1354430357562464]

    preferred_configuration_weight: [0, 1, 1, 1, 1, 1]
    max_ik_goal_number: 512
    use_single_goal: false

  request_adapters:
  - default_planner_request_adapters/AddTimeParameterization
  - default_planner_request_adapters/FixWorkspaceBounds
  - default_planner_request_adapters/FixStartStateBounds
  - default_planner_request_adapters/FixStartStateCollision
  - default_planner_request_adapters/FixStartStatePathConstraints
