object_geometries:
  blank_piece_location:
    color: [1,0.8,0,1.0]
    box:  [0.03,0.03,0.01]
    offset: [0.0,0.0,0.005]

  squadra_piccola:
    # color: [0.2,0.2,0.2, 1.]
    box:  [0.019,0.03,0.012]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  pin:
    # color: [0.2,0.2,0.2, 0.4]
    box:  [0.02,0.02,0.03]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  squadra_grande:
    # color: [0.2,0.2,0.2, 1.]
    box:  [0.03,0.01,0.03]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  cube:
    # color: [0.2,0.2,0.2, 0.4]
    box:  [0.03,0.03,0.03]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  little_cube:
    box:  [0.015,0.015,0.015]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  plate:
    box: [0.17,0.01,0.025]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  L_plate:
    box: [0.16,0.03,0.03]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]
