manipulation_objects_geometry:
  oggetto_prova:
    color: [0.2,0.2,0.2, 0.4]
    box:  [0.03,0.03,0.03]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  blank_piece_location:
    color: [1,0.8,0,1.0]
    box:  [0.04,0.04,0.01]
    offset: [0.0,0.0,0.005]

  squadra_piccola:
    color: [0.2,0.2,0.2, 1.]
    box:  [0.019,0.03,0.012]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  pin:
    color: [0.2,0.2,0.2, 0.4]
    box:  [0.02,0.02,0.03]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  squadra_grande:
    color: [0.2,0.2,0.2, 1.]
    box:  [0.03,0.01,0.03]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  cube:
    color: [0.2,0.2,0.2, 0.4]
    box:  [0.03,0.03,0.03]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]
